**QuTiP**  
<span style="color:blue"> A python package for calculations and numerical simulations of quantum systems. </span>

In [1]:
#conda list

In [2]:
#from qutip.ipynbtools import version_table

#version_table()

In [3]:
import matplotlib.pyplot as plt
import numpy as np
from IPython.display import Image

In [4]:
import qutip as qu

In [59]:
#Image(filename='images/qobj.png')

In [6]:
q = qu.Qobj([[1], [0]])
q

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]

In [10]:
# the dimension, or composite Hilbert state space structure
q.dims

[[2], [1]]

In [11]:
q.shape

(2, 1)

In [12]:
q.data

<2x1 sparse matrix of type '<class 'numpy.complex128'>'
	with 1 stored elements in Compressed Sparse Row format>

In [13]:
# get the dense matrix representation
q.full()

array([[1.+0.j],
       [0.+0.j]])

In [14]:
q.type

'ket'

**Pauli Matrices**

$\sigma_1=\sigma_x=\left(\begin{array}{cc} 
0 & 1\\ 
1 & 0
\end{array}\right)
$$, \ \ \ \ \ \sigma_2=\sigma_y=\left(\begin{array}{cc} 
0 & -i\\ 
i & 0
\end{array}\right)
$$ , \ \ \ \ \ \sigma_3=\sigma_z=\left(\begin{array}{cc} 
1 & 0\\ 
0 & -1
\end{array}\right)
$$ $

With `Qobj` instances we can do arithmetic and apply a number of different operations using class methods:

In [43]:
sy = qu.Qobj([[0, -1j], [1j, 0]]) # Pauli matrix
sy

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j]]

In [19]:
sx = qu.Qobj([[0, 1], [1, 0]]) #sigma_x
sx

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 1.]
 [1. 0.]]

In [20]:
sy.type #Operator

'oper'

In [22]:
H = 1.0 * qu.Qobj([[1, 0], [0, -1]]) + 0.1 * sy
print("Qubit Hamiltonian = \n")
H

Qubit Hamiltonian = 



Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.+0.j   0.-0.1j]
 [ 0.+0.1j -1.+0.j ]]

In [30]:
print(q.dag().type)
q.dag()

bra


Quantum object: dims = [[1], [2]], shape = (1, 2), type = bra
Qobj data =
[[1. 0.]]

In [31]:
# The hermitian conjugate
sy.dag()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j]]

In [102]:
q.dag().isherm

False

In [32]:
H.tr()

0.0

In [33]:
# Eigen Energies
H.eigenenergies()

array([-1.00498756,  1.00498756])

In [36]:
H.eigenstates()

(array([-1.00498756,  1.00498756]),
 array([Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
 Qobj data =
 [[-0.0498137+0.j        ]
  [ 0.       +0.99875853j]],
        Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
 Qobj data =
 [[-0.99875853+0.j       ]
  [ 0.        -0.0498137j]]], dtype=object))

In [37]:
dir(qu.Qobj)

['__abs__',
 '__add__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__pow__',
 '__radd__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__rsub__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '_repr_latex_',
 'check_herm',
 'check_isunitary',
 'conj',
 'copy',
 'cosm',
 'dag',
 'data',
 'diag',
 'dnorm',
 'dual_chan',
 'eigenenergies',
 'eigenstates',
 'eliminate_states',
 'evaluate',
 'expm',
 'extract_states',
 'full',
 'get_data',
 'groundstate',
 'inv',
 'isbra',
 'iscp',
 'iscptp',
 'isherm',
 'ishp',
 'isket',
 'isoper',
 'isoperbra',
 'isoperket',
 

In [38]:
q.conj()

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]

In [39]:
q.dag()

Quantum object: dims = [[1], [2]], shape = (1, 2), type = bra
Qobj data =
[[1. 0.]]

In [40]:
sy.conj()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.+1.j]
 [0.-1.j 0.+0.j]]

In [45]:
q.check_herm()

False

In [49]:
np.dot(q, q.dag())

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j]])

### Sates and operators  
We can use some functions in QuTiP that <span style="color:blue"> generate common states and operators </span> for us, instead of create `Qobj` instances. Some example of built-in state funtions

In [56]:
N = 3 #number of states in Hilbert space
n = 2 # the state that will be occupied

qu.basis(N, n) #equivalent to fock(N, n) 

Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [1.]]

In [62]:
# another example
qu.fock(4, 3)

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [1.]]

In [61]:
qu.coherent(N=10, alpha=2.0)

Quantum object: dims = [[10], [1]], shape = (10, 1), type = ket
Qobj data =
[[0.13533468]
 [0.27067598]
 [0.38275331]
 [0.44215515]
 [0.4414275 ]
 [0.39717038]
 [0.31781378]
 [0.25575028]
 [0.14827955]
 [0.15941954]]

**Density matrices** 

In [77]:
# a fock state as density matrix
qu.fock_dm(5, 2)# Hilbert space size = 5, State that is occupied=2


Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

In [78]:
qu.coherent_dm(N=8, alpha=2.0)

Quantum object: dims = [[8], [8]], shape = (8, 8), type = oper, isherm = True
Qobj data =
[[0.01830246 0.03666452 0.05157071 0.06055134 0.05768137 0.05837903
  0.03413136 0.04895908]
 [0.03666452 0.0734484  0.10330932 0.12129983 0.11555054 0.11694813
  0.06837385 0.09807755]
 [0.05157071 0.10330932 0.14531038 0.17061505 0.16252835 0.16449414
  0.09617168 0.13795161]
 [0.06055134 0.12129983 0.17061505 0.20032632 0.1908314  0.19313951
  0.11291922 0.1619748 ]
 [0.05768137 0.11555054 0.16252835 0.1908314  0.1817865  0.18398522
  0.10756716 0.15429763]
 [0.05837903 0.11694813 0.16449414 0.19313951 0.18398522 0.18621053
  0.10886819 0.15616387]
 [0.03413136 0.06837385 0.09617168 0.11291922 0.10756716 0.10886819
  0.0636499  0.09130138]
 [0.04895908 0.09807755 0.13795161 0.1619748  0.15429763 0.15616387
  0.09130138 0.1309655 ]]

In [80]:
# thermal state
n = 1 # average number of thermal photons
qu.thermal_dm(8, n)

Quantum object: dims = [[8], [8]], shape = (8, 8), type = oper, isherm = True
Qobj data =
[[0.50196078 0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.25098039 0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.1254902  0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.0627451  0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.03137255 0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.01568627
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.00784314 0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.00392157]]

### Operators
Qubit(two level system) operators

In [96]:
# Pauli sigma x, y, z
print('$\sigma_x$ = ', qu.sigmax())
print('$\sigma_y$ = ', qu.sigmay())
print('$\sigma_z$ = ', qu.sigmaz())

$\sigma_x$ =  Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 1.]
 [1. 0.]]
$\sigma_y$ =  Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j]]
$\sigma_z$ =  Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]


### Harmonic oscillator operators

In [97]:
#  annihilation operator

qu.destroy(N=8) # N = number of fock states included in the Hilbert space

Quantum object: dims = [[8], [8]], shape = (8, 8), type = oper, isherm = False
Qobj data =
[[0.         1.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         1.41421356 0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         1.73205081 0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         2.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         2.23606798
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  2.44948974 0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         2.64575131]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]]

In [99]:
# creation operator

qu.create(N=8) # equivalent to destroy(5).dag()

Quantum object: dims = [[8], [8]], shape = (8, 8), type = oper, isherm = False
Qobj data =
[[0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [1.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         1.41421356 0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         1.73205081 0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         2.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         2.23606798 0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         2.44948974
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  2.64575131 0.        ]]

In [103]:
H.isherm

True